app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path: /homepage
    defaults: { _controller: AppBundle:Homepage:homepage}

contact:
    path: /contact
    defaults: { _controller: AppBundle:Contact:contact}
