app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path: /homepage
    defaults: { _controller: AppBundle:Homepage:homepage}

contact:
    path: /contact
    defaults: { _controller: AppBundle:Contact:contact}

about-me:
    path: /about-me
    defaults: { _controller: AppBundle:About:about}

test:
    path: /test
    defaults: { _controller: AppBundle:Test:test}
